### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by poinch** [jchip/nvm#10]
Can you please share a way to how to uninstall the package?

**Comment by jchip** [comment]
## Windows

Delete nvm directory from home directory

Use RegEdit, and delete `NVM_HOME` and `NVM_LINK` from `HKEY_CURRENT_USER`->`Environment`

## Unix

`rm -rf ~/nvm`

then remove these from your shell rc file, like `~/.bashrc` or `~/.zshrc`

```
# NVM zsh initialize BEGIN - do not modify #
export NVM_HOME="${HOME}/nvm"
NVM_SH="${NVM_HOME}/bin/nvm.sh"
if [ -s "${NVM_SH}" ]; then
  export NVM_LINK="${HOME}/nvm/nodejs/bin"
  source "${NVM_SH}"
else
  unset NVM_HOME
  NVM_ERROR="${NVM_SH} is not valid"
fi
unset NVM_SH
# NVM zsh initialize END - do not modify #
```
