### ISSUE TITLE
Missing settings.txt

### ISSUE THREAD

**Issue by bhemsen** [jchip/nvm#5]
Hi, thanks for the project

I followed your instructions and run the script in Windows Powershell (5.1 / Windows 10). It runs successfully and says NVM installed, Node.js version v12.16.0 activated. 
When i want to use nvm commants i get an error "...\settings.txt is missing. 
What did i do wrong?

**Comment by jchip** [comment]
I think you have another windows nvm installed, and you've installed my windows nvm on top of that.
